### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by roozbehes** [data301-2020-winter1/course-project-solo_100#1]
Excellent work !!

Here are a few pointers:

- [x] The purpose of moving "load_and_process_anime" function to a separate file is that you remove it from your notebook and just call a function to take care of data loading

- [x] when you use describe() function function you should remove the id columns. calculating mean, std , quantiles, etc, of an id columns doesn't provide any usefull knowledge

- [x] you can use df.name.unique() to get the unique values of a column

**Comment by aadiraju** [comment]
I have addressed these issues and rectified them, except for the last one. It ended up being that I can't use df.name.unique() on my genre column since **each element is a list and therefore unhashable**. I ended up acknowledging that we could use this but it doesn't work in this case, so I stuck with the bespoke method I made in the notebook. 

Thank you for the Feedback! :)
